language: python
python: 
        - "2.6"
        - "2.7"
        - "3.2"
        - "3.3"
        - "3.4"

# dependencies
install:
        - "pip install -q dnsq"
        - "pip install -q flask"

# fireup app
script: txtproxy.py
